### ISSUE TITLE
'; being output in slide nav

### ISSUE THREAD

**Issue by michaelbeil** [wpdevelopersclub/WPDevsClub-Child-Theme#1]
![screen shot 2015-04-27 at 22 51 46](https://cloud.githubusercontent.com/assets/4752949/7362544/32a5c504-ed30-11e4-8fb5-975cb47832ac.png)
![screen shot 2015-04-27 at 10 52 35 pm](https://cloud.githubusercontent.com/assets/4752949/7362546/360ae10c-ed30-11e4-8953-aa4c40693c4c.png)

Safari 8.0.5

**Comment by hellofromtonya** [comment]
Hello Michael, Thank you for pointing that out to me.  I just pushed a rev to correct those left over PHP junk. </>

**Comment by michaelbeil** [comment]
saweet! :+1:
