### ISSUE TITLE
Don't pass a plain text password

### ISSUE THREAD

**Issue by michaelbeil** [wpdevelopersclub/WPDevsClub-Child-Theme#2]
The following activation email is sent to the user: 

```
To activate your user, please click the following link:

http://wpdevelopersclub.com/?page=gf_activation&key=xxxxxxxxxxxxxx

After you activate, you will receive *another email* with your login.
```

After clicking the link, the password is displayed on the page in plain text.

Perhaps passing `(password chosen at registration)` instead is a better solution?

**Comment by hellofromtonya** [comment]
Hello Michael,

I just switched the site over to SSL for the entire site.  Now when they click on the activation link and it displays their password on the screen, it will protected.  As this is sitewide, everything is protected now.

Cheers,
Tonya

**Comment by michaelbeil** [comment]
Perfect! Still could be good to pass a `(chosen password)` statement in place of the password itself, but now that the site is SSL, that's great.
